a la imagen base de Nginx Alpine
FROM nginx:alpine

# Copia el archivo de configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expon el puerto 80 para Nginx
EXPOSE 80

# Comando para iniciar Nginx en segundo plano
CMD ["nginx", "-g", "daemon off;"]
